name: Run Tests

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run tests
        run: make test
